server:
  port: 8080
  error:
    include-stacktrace: never
---
spring:
  devtools:
    livereload:
      enabled: true
  main:
    lazy-initialization: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-red-mouse-31349640.ap-southeast-1.aws.neon.tech/neondb?user=robinkhoa06&password=T3HiNgy4nawX # jdbc:postgresql://127.0.0.1:5432/intelliedu
    username: robinkhoa06 
    password: T3HiNgy4nawX
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  web:
    resources:
      static-locations: file:${user.dir}/../Frontend/
---
