spring:
  datasource:
    url: jdbc:postgresql://ep-nameless-cake-76008135.ap-southeast-1.aws.neon.tech/neondb
    username: robinkhoa06 
    password: DoHMj8tam4LY
  jpa:
    hibernate:
      ddl-auto: update
  web:
    resources:
      static-locations: file:/Frontend/

