server:
  port: 12345
  error:
    include-message: always
    include-stacktrace: never
---
spring:
  mvc:
    async:
      request-timeout: -1 
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maxLifeTime: 300000
---
python:
  port: 54321
