spring:
  main:
    lazy-initialization: true
  datasource:
    url: jdbc:postgresql://ep-winter-brook-48494983.ap-southeast-1.aws.neon.tech/Intelli%20Edu?user=robinkhoa06&password=Dq5loepZr8PW&sslmode=require
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  web:
    resources:
      static-locations: file:/media/Data/Project/Intelli-Edu/Frontend,
                        file:/media/Data/Project/Intelli-Edu/Frontend/homepage/build/,
                        file:/media/Data/Project/Intelli-Edu/Frontend/mindmap/dist/,
                        file:/media/Data/Project/Intelli-Edu/Frontend/todo-list/dist/,
                        file:/Frontend,
                        file:/Frontend/homepage/build/,
                        file:/Frontend/mindmap/dist/,
                        file:/Frontend/todo-list/dist/
---
domain: localhost:8080
