spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/intelliedu
    username: postgres 
    password: 1234567890
  jpa:
    hibernate:
      ddl-auto: update 
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  web:
    resources:
      static-locations: file:${user.dir}/../Frontend/

