server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: never
---
spring:
  mvc:
    async:
      request-timeout: -1 
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maxLifeTime: 300000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
---
python:
  port: 65432
