spring:
  main:
    lazy-initialization: true
  datasource:
    url: ${DATABASE_TEST}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  web:
    resources:
      static-locations: file:/media/Data/Project/Intelli-Edu/Frontend,
                        file:/media/Data/Project/Intelli-Edu/Frontend/homepage/build/,
                        file:/media/Data/Project/Intelli-Edu/Frontend/mindmap/dist/,
                        file:/media/Data/Project/Intelli-Edu/Frontend/todo-list/dist/,
                        file:/Frontend,
                        file:/Frontend/homepage/build/,
                        file:/Frontend/mindmap/dist/,
                        file:/Frontend/todo-list/dist/
---
domain: localhost:8080
