spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/intelliedu
    username: postgres 
    password: 1234567890
  web:
    resources:
      static-locations: file:${user.dir}/../Frontend/

