# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
    paths: "Backend/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: "17"
        distribution: "temurin"
        cache: maven
    
    - name: Build with Maven
      run: mvn package -q -f Backend/pom.xml -Dspring.profiles.active=test

  dockerize:
    name: Dockerize
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR }}

      - name: Build and tag Docker image
        run: |
          docker build -f Backend/test.Dockerfile -t ghcr.io/khoanguyenducanh/intelli-edu:test .

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/khoanguyenducanh/intelli-edu:test
